name = "veysel-aslan"
type = "javascript"
compatibility_date = "2026-05-15"

[build]
command = "echo 'No build required for static site'"

[build.upload]
format = "service-worker"

[assets]
directory = "."
include = ["*.html", "*.css", "*.js", "*.json"]
