pages_build_output_dir = "."

[build]
command = "echo 'No build needed'"
cwd = "."

[env.production]
name = "veysel-aslan"
routes = [
  { pattern = "veyselaslan.com/*", zone_name = "veyselaslan.com" }
]
