name = "veysel-aslan"
type = "javascript"
account_id = "YOUR_ACCOUNT_ID"
workers_dev = true

[env.production]
routes = [
  { pattern = "veyselaslan.com/*", zone_name = "veyselaslan.com" }
]

[site]
bucket = "."
include = ["*.html", "*.css", "*.js"]
